version: 0.2

phases:
  build:
    commands:
      - echo entered the build phase..
      - mvn clean package
  post_build:
    commands:
      - echo build completed successfull..
artifacts:
  files:
    - target/cicd-finalname.jar
  discard-paths: yes